services:
  - name: minio
    type: web
    plan: starter
    region: frankfurt
    env:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    port: 9001
    docker:
      image: minio/minio:latest
      volumes:
        - ./data:/data