services:
  - name: minio
    type: web
    plan: starter
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MINIO_ROOT_USER
        value: admin
      - key: MINIO_ROOT_PASSWORD
        value: password
    disk:
      name: minio-data
      mountPath: /data
      sizeGB: 10
    healthCheckPath: /minio/health/live
    runtime: docker
